#include "MetroidPrime/Tweaks/CTweakAutoMapper.hpp"

#include "Kyoto/Streams/CInputStream.hpp"

CTweakAutoMapper::~CTweakAutoMapper() {}

CTweakAutoMapper::CTweakAutoMapper(CInputStream& in)
  : mShowOneMiniMapArea(in.ReadBool())
  , x4_25_(in.ReadBool())
  , mScaleMoveSpeedWithCamDist(in.ReadBool())
  , mCamDist(in.ReadFloat())
  , mMinCamDist(in.ReadFloat())
  , mMaxCamDist(in.ReadFloat())
  , mMinCamRotateX(in.ReadFloat())
  , mMaxCamRotateX(in.ReadFloat())
  , mCamAngle(in.ReadFloat())
  , x20_(in.ReadFloat())
  , mAutomapperWidgetColor(in)
  , mMiniCamDist(in.ReadFloat())
  , mMiniCamXAngle(in.ReadFloat())
  , mMiniCamAngle(in.ReadFloat())
  , x34_(in.ReadFloat())
  , mAutomapperWidgetMiniColor(in)
  , mSurfColorVisited(in)
  , mOutlineColorVisited(in)
  , mSurfColorUnvisited(in)
  , mOutlineColorUnvisited(in)
  , mSurfaceSelectColorVisited(in)
  , mOutlineSelectColorVisited(in)
  , mMapSurfaceNormColorLinear(in.ReadFloat())
  , mMapSurfaceNormColorConstant(in.ReadFloat())
  , x5c_(in.ReadFloat())
  , x60_(0.4f)
  , mOpenMapScreenTime(in.ReadFloat())
  , mCloseMapScreenTime(in.ReadFloat())
  , mHintPanTime(in.ReadFloat())
  , mZoomUnitsPerFrame(in.ReadFloat())
  , mRotateDegPerFrame(in.ReadFloat())
  , mBaseMapScreenCameraMoveSpeed(in.ReadFloat())
  , mSurfaceSelectColorUnvisited(in)
  , mOutlineSelectColorUnvisited(in)
  , mMiniAlphaSurfaceVisited(in.ReadFloat())
  , mAlphaSurfaceVisited(in.ReadFloat())
  , mMiniAlphaOutlineVisited(in.ReadFloat())
  , mAlphaOutlineVisited(in.ReadFloat())
  , mMiniAlphaSurfaceUnvisited(in.ReadFloat())
  , mAlphaSurfaceUnvisited(in.ReadFloat())
  , mMiniAlphaOutlineUnvisited(in.ReadFloat())
  , mAlphaOutlineUnvisited(in.ReadFloat())
  , mDoorCenterA(in.ReadFloat())
  , mDoorCenterB(in.ReadFloat())
  , mDoorCenterC(in.ReadFloat())
  , xb0_(in.ReadFloat())
  , xb4_(in.ReadFloat())
  , mMiniMapViewportWidth(in.ReadFloat())
  , mMiniMapViewportHeight(in.ReadFloat())
  , mMiniMapCamDistScale(in.ReadFloat())
  , mMapPlaneScaleX(in.ReadFloat())
  , mMapPlaneScaleZ(in.ReadFloat())
  , xcc_(in.ReadBool())
  , mUniverseCamDist(in.ReadFloat())
  , mMinUniverseCamDist(in.ReadFloat())
  , mMaxUniverseCamDist(in.ReadFloat())
  , mSwitchToFromUniverseTime(in.ReadFloat())
  , mCamPanUnitsPerFrame(in.ReadFloat())
  , mAutomapperScaleX(in.ReadFloat())
  , mAutomapperScaleZ(in.ReadFloat())
  , mCamVerticalOffset(in.ReadFloat())
  , mMiniMapSamusModColor(in)
  , mAreaFlashPulseColor(in)
  , xf8_(in)
  , xfc_(in)
  , mDoorColors(in)
  , mDoorBorderColor(in)
  , mOpenDoorColor(in)
{
  mSurfColorVisited.SetAlpha(1.0f);
  mOutlineColorVisited.SetAlpha(1.0f);
  mSurfColorUnvisited.SetAlpha(1.0f);
  mOutlineColorUnvisited.SetAlpha(1.0f);
}
