#include "MetroidPrime/Tweaks/CTweakTargeting.hpp"

#include "Kyoto/Math/CMath.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

CTweakTargeting::CTweakTargeting(CInputStream& in)
: mTargetRadiusMode(in.ReadLong())
, mCurrLockOnExitDuration(in.ReadFloat())
, mCurrLockOnEnterDuration(in.ReadFloat())
, mCurrLockOnSwitchDuration(in.ReadFloat())
, mLockConfirmScale(in.ReadFloat())
, mNextLockOnEnterDuration(in.ReadFloat())
, mNextLockOnExitDuration(in.ReadFloat())
, mNextLockOnSwitchDuration(in.ReadFloat())
, mSeekerScale(in.ReadFloat())
, mSeekerAngleSpeed(in.ReadFloat())
, mXrayRetAngleSpeed(in.ReadFloat())
, x30_(in)
, x3c_(in)
, x48_(in.ReadFloat())
, x4c_(in.ReadFloat())
, mOrbitPointZOffset(in.ReadFloat())
, mOrbitPointInTime(in.ReadFloat())
, mOrbitPointOutTime(in.ReadFloat())
, x5c_(in.ReadFloat())
, x60_(in)
, x6c_(in)
, x78_(in)
, x84_(in)
, x90_(in.ReadFloat())
, x94_(in.ReadFloat())
, x98_(in.ReadFloat())
, x9c_(in.ReadFloat())
, xa0_(in.ReadFloat())
, xa4_(in.ReadFloat())
, xa8_(in.ReadFloat())
, xac_(in.ReadFloat())
, mThermalReticuleColor(in)
, mTargetFlowerScale(in.ReadFloat())
, mTargetFlowerColor(in)
, mMissileBracketDuration(in.ReadFloat())
, mMissileBracketScaleStart(in.ReadFloat())
, mMissileBracketScaleEnd(in.ReadFloat())
, mMissileBracketScaleDuration(in.ReadFloat())
, mMissileBracketColor(in)
, mLockonDuration(in.ReadFloat())
, mInnerBeamScale(in.ReadFloat())
, mInnerBeamColorPower(in)
, mInnerBeamColorIce(in)
, mInnerBeamColorWave(in)
, mInnerBeamColorPlasma(in)
, mChargeGaugeOvershootOffset(in.ReadFloat())
, mChargeGaugeOvershootDuration(in.ReadFloat())
, mOuterBeamSquaresScale(in.ReadFloat())
, mOuterBeamSquareColor(in)
, mOuterBeamSquareAngles(in)
, mChargeGaugeAngles(in)
, mChargeGaugeScale(in.ReadFloat())
, mChargeGaugeNonFullColor(in)
, mChargeTickCount(in.ReadLong())
, mChargeTickAnglePitch(-1.f * CMath::Deg2Rad(in.ReadFloat()))
, mLockFireScale(in.ReadFloat())
, mLockFireDuration(in.ReadFloat())
, mLockFireColor(in)
, mLockDaggerScaleStart(in.ReadFloat())
, mLockDaggerScaleEnd(in.ReadFloat())
, mLockDaggerColor(in)
, mLockDaggerAngle0(CMath::Deg2Rad(in.ReadFloat()))
, mLockDaggerAngle1(CMath::Deg2Rad(in.ReadFloat()))
, mLockDaggerAngle2(CMath::Deg2Rad(in.ReadFloat()))
, mLockConfirmColor(in)
, mSeekerColor(in)
, mLockConfirmClampMin(in.ReadFloat())
, mLockConfirmClampMax(in.ReadFloat())
, mTargetFlowerClampMin(in.ReadFloat())
, mTargetFlowerClampMax(in.ReadFloat())
, mSeekerClampMin(in.ReadFloat())
, mSeekerClampMax(in.ReadFloat())
, mMissileBracketClampMin(in.ReadFloat())
, mMissileBracketClampMax(in.ReadFloat())
, mInnerBeamClampMin(in.ReadFloat())
, mInnerBeamClampMax(in.ReadFloat())
, mChargeGaugeClampMin(in.ReadFloat())
, mChargeGaugeClampMax(in.ReadFloat())
, mLockFireClampMin(in.ReadFloat())
, mLockFireClampMax(in.ReadFloat())
, mLockDaggerClampMin(in.ReadFloat())
, mLockDaggerClampMax(in.ReadFloat())
, mGrappleSelectScale(in.ReadFloat())
, mGrappleScale(in.ReadFloat())
, mGrappleClampMin(in.ReadFloat())
, mGrappleClampMax(in.ReadFloat())
, mGrapplePointSelectColor(in)
, mGrapplePointColor(in)
, mLockedGrapplePointSelectColor(in)
, mGrappleMinClampScale(in.ReadFloat())
, mChargeGaugePulseColorHigh(in)
, mFullChargeFadeDuration(in.ReadFloat())
, mOrbitPointColor(in)
, mCrosshairsColor(in)
, mCrosshairsScaleDur(in.ReadFloat())
, mDrawOrbitPoint(in.ReadBool())
, mChargeGaugePulseColorLow(in)
, mChargeGaugePulsePeriod(in.ReadFloat())
, x1d4_(in)
, x1d8_(in)
, x1dc_(in)
, x1e0_(in.ReadFloat())
, x1e4_(in.ReadFloat())
, x1e8_(in.ReadFloat())
, x1ec_(in.ReadFloat())
, x1f0_(in.ReadFloat())
, x1f4_(in.ReadFloat())
, x1f8_(in.ReadFloat())
, x1fc_(in.ReadFloat())
, x200_(in.ReadFloat())
, x204_(in.ReadFloat())
, x208_(in.ReadFloat())
, mReticuleClampMin(in.ReadFloat())
, mReticuleClampMax(in.ReadFloat())
, mXrayRetRingColor(in)
, mReticuleScale(in.ReadFloat())
, mScanTargetClampMin(in.ReadFloat())
, mScanTargetClampMax(in.ReadFloat())
, mAngularLagSpeed(in.ReadFloat()) {
  x208_ = CMath::Deg2Rad(x208_);

  for (int i = 0; i < 4; ++i) {
    rstl::vector< float >& angles = mOuterBeamSquareAngles[i];
    for (int j = 0; j < 9; ++j) {
      float& angle = angles[j];
      angle = CMath::Deg2Rad(angle);
    }
  }

  for (int i = 0; i < 4; ++i) {
    mChargeGaugeAngles[i] = CMath::Deg2Rad(mChargeGaugeAngles[i]);
  }
}
