#include "MetroidPrime/Tweaks/CTweakGui.hpp"

#include "Kyoto/Graphics/CGraphics.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

static inline ERglFogMode read_fog_mode(CInputStream& in) {
  switch (in.ReadInt32()) {
  case 0:
    return kRFM_None;
  case 1:
    return kRFM_PerspLin;
  case 2:
    return kRFM_PerspExp;
  case 3:
    return kRFM_PerspExp2;
  default:
    return kRFM_None;
  }
}

CTweakGui::CTweakGui(CInputStream& in)
: x4_(in.ReadBool())
, mMapAlphaInterp(in.ReadFloat())
, mPauseBlurFactor(in.ReadFloat())
, mRadarXYRadius(in.ReadFloat())
, x14_(in.ReadFloat())
, x18_(in.ReadFloat())
, x1c_(in.ReadFloat())
, x20_(in.ReadFloat())
, mRadarZRadius(in.ReadFloat())
, mRadarZCloseRadius(in.ReadFloat())
, x2c_(0)
, x30_(in.ReadFloat())
, mEnergyBarFilledSpeed(in.ReadFloat())
, mEnergyBarShadowSpeed(in.ReadFloat())
, mEnergyBarDrainDelay(in.ReadFloat())
, mEnergyBarAlwaysResetDelay(in.ReadBool())
, mHudDamagePracticalsGainConstant(in.ReadFloat())
, mHudDamagePracticalsGainLinear(in.ReadFloat())
, mHudDamagePracticalsInitConstant(in.ReadFloat())
, mHudDamagePracticalsInitLinear(in.ReadFloat())
, mHudDamageLightSpotAngle(in.ReadFloat())
, mDamageLightAngleC(in.ReadFloat())
, mDamageLightAngleL(in.ReadFloat())
, mDamageLightAngleQ(in.ReadFloat())
, mDamageLightPreTranslate(in)
, mDamageLightCenterTranslate(in)
, mDamageLightXfXAngle(in.ReadFloat())
, mDamageLightXfZAngle(in.ReadFloat())
, mHudDecoShakeTranslateVelConstant(in.ReadFloat())
, mHudDecoShakeTranslateVelLinear(in.ReadFloat())
, mMaxDecoDamageShakeTranslate(in.ReadFloat())
, mDecoDamageShakeDeceleration(in.ReadFloat())
, mDecoShakeGainConstant(in.ReadFloat())
, mDecoShakeGainLinear(in.ReadFloat())
, mDecoShakeInitConstant(in.ReadFloat())
, mDecoShakeInitLinear(in.ReadFloat())
, mMaxDecoDamageShakeRotate(in.ReadFloat())
, mHudCamFovTweak(in.ReadInt32())
, mHudCamYTweak(in.ReadInt32())
, mHudCamZTweak(in.ReadInt32())
, xb4_(in.ReadFloat())
, xb8_(in.ReadFloat())
, xbc_(in.ReadFloat())
, mBeamVisorMenuAnimTime(in.ReadFloat())
, mVisorBeamMenuItemActiveScale(in.ReadFloat())
, mVisorBeamMenuItemInactiveScale(in.ReadFloat())
, mVisorBeamMenuItemTranslate(in.ReadFloat())
, xd0_(in.ReadFloat())
, xd4_(in.ReadInt32())
, xd8_(CMath::Deg2Rad(in.ReadFloat()))
, xdc_(CMath::Deg2Rad(in.ReadFloat()))
, xe0_(in.ReadFloat())
, mThreatRange(in.ReadFloat())
, mRadarScopeCoordRadius(in.ReadFloat())
, mRadarPlayerPaintRadius(in.ReadFloat())
, mRadarEnemyPaintRadius(in.ReadFloat())
, mMissileArrowVisTime(in.ReadFloat())
, mHudVisMode(static_cast< EHudVisMode >(in.ReadInt32()))
, mHelmetVisMode(static_cast< EHelmetVisMode >(in.ReadInt32()))
, mEnableAutoMapper(in.ReadInt32())
, x104_(in.ReadInt32())
, mEnableTargetingManager(in.ReadInt32())
, mEnablePlayerVisor(in.ReadInt32())
, mThreatWarningFraction(in.ReadFloat())
, mMissileWarningFraction(in.ReadFloat())
, mFreeLookFadeTime(in.ReadFloat())
, x11c_(in.ReadFloat())
, x120_(in.ReadFloat())
, x124_(in.ReadFloat())
, x128_(in.ReadFloat())
, mFreeLookSfxPitchScale(in.ReadFloat())
, mNoAbsoluteFreeLookSfxPitch(in.ReadBool())
, x134_(in.ReadFloat())
, x138_(in.ReadFloat())
, mFaceReflectionOrthoWidth(in.ReadInt32())
, mFaceReflectionOrthoHeight(in.ReadInt32())
, mFaceReflectionDistance(in.ReadInt32())
, mFaceReflectionHeight(in.ReadInt32())
, mFaceReflectionAspect(in.ReadInt32())
, x150_(in)
, x160_(in)
, x170_(in)
, x180_(in)
, x190_(in)
, mMissileWarningPulseTime(in.ReadFloat())
, mExplosionLightFalloffMultConstant(in.ReadFloat())
, mExplosionLightFalloffMultLinear(in.ReadFloat())
, mExplosionLightFalloffMultQuadratic(in.ReadFloat())
, x1b0_(in.ReadFloat())
, mHudDamagePeakFactor(in.ReadFloat())
, mHudDamageFilterGainConstant(in.ReadFloat())
, mHudDamageFilterGainLinear(in.ReadFloat())
, mHudDamageFilterInitConstant(in.ReadFloat())
, mHudDamageFilterInitLinear(in.ReadFloat())
, mEnergyDrainModPeriod(in.ReadFloat())
, mEnergyDrainSinusoidalPulse(in.ReadBool())
, mEnergyDrainFilterAdditive(in.ReadBool())
, mHudDamagePulseDuration(in.ReadFloat())
, mHudDamageColorGain(in.ReadFloat())
, mHudDecoShakeTranslateGain(in.ReadFloat())
, mHudLagOffsetScale(in.ReadFloat())
, x1e0_(in.ReadFloat())
, x1e4_(in.ReadFloat())
, x1e8_(in.ReadFloat())
, x1ec_(in.ReadFloat())
, x1f0_(in.ReadFloat())
, x1f4_(in.ReadFloat())
, x1f8_(in.ReadFloat())
, x1fc_(in.ReadFloat())
, x200_(x1f4_ * 0.25f, x1f8_ * 0.25f, x1fc_ * 0.25f)
, mXrayBlurScaleLinear(0.0014f)
, mXrayBlurScaleQuadratic(0.0000525f)
, x20c_(in.ReadFloat())
, mScanSidesAngle(CMath::Deg2Rad(in.ReadFloat()))
, mScanSidesXScale(in.ReadFloat())
, mScanSidesPositionEnd(in.ReadFloat())
, x21c_(in.ReadFloat())
, mScanSidesDuration(in.ReadFloat())
, mScanSidesStartTime(in.ReadFloat())
, mScanSidesEndTime(mScanSidesDuration + mScanSidesStartTime)
, mScanDataDotRadius(in.ReadFloat())
, mScanDataDotPosRandMag(in.ReadFloat())
, mScanDataDotSeekDurationMin(in.ReadFloat())
, mScanDataDotSeekDurationMax(in.ReadFloat())
, mScanDataDotHoldDurationMin(in.ReadFloat())
, mScanDataDotHoldDurationMax(in.ReadFloat())
, mScanAppearanceDuration(in.ReadFloat())
, mScanPaneFlashFactor(in.ReadFloat())
, mScanPaneFadeInTime(in.ReadFloat())
, mScanPaneFadeOutTime(in.ReadFloat())
, mBallViewportYReduction(in.ReadFloat())
, mScanWindowIdleW(in.ReadFloat())
, mScanWindowIdleH(in.ReadFloat())
, mScanWindowActiveW(in.ReadFloat())
, mScanWindowActiveH(in.ReadFloat())
, mScanWindowMagnification(in.ReadFloat())
, mScanWindowScanningAspect(in.ReadFloat())
, mScanSidesPositionStart(in.ReadFloat())
, mShowAutomapperInMorphball(in.ReadBool())
, mLatchArticleText(true)
, mWtMgrCharsPerSfx(in.ReadFloat())
, mXrayFogMode(read_fog_mode(in))
, mXrayFogNearZ(in.ReadFloat())
, mXrayFogFarZ(in.ReadFloat())
, mXrayFogColor(in)
, mThermalVisorLevel(in.ReadFloat())
, mThermalVisorColor(in)
, mCombatVisorHudLightAdd(in)
, mXRayVisorHudLightAdd(in)
, mScanVisorHudLightAdd(in)
, mThermalVisorHudLightAdd(in)
, mCombatVisorHudLightMultiply(in)
, mXRayVisorHudLightMultiply(in)
, mScanVisorHudLightMultiply(in)
, mThermalVisorHudLightMultiply(in)
, mHudReflectivityLightColor(in)
, mHudLightAttMulConstant(in.ReadFloat())
, mHudLightAttMulLinear(in.ReadFloat())
, mHudLightAttMulQuadratic(in.ReadFloat())
, mScanSpeeds(in)
, mCreditsTable(in)
, mCreditsFont(in)
, mJapaneseCreditsFont(in)
, mCreditsTextFontColor(in)
, mCreditsTextBorderColor(in)
, x308_(in.ReadFloat())
, x30c_(in.ReadFloat())
, x310_(in.ReadFloat())
, x314_(in)
, x324_(in)
, x334_(in)
, mCompletionTitleColor(in)
, mCompletionTitleOutlineColor(in)
, mCompletionBodyColor(in)
, mCompletionBodyOutlineColor(in)
, mCompletionUnlockColor(in)
, mCompletionUnlockOutlineColor(in)
, x35c_(in.ReadFloat())
, x360_(in.ReadFloat())
, x364_(in.ReadFloat()) {
  mHudDecoShakeTranslateVelConstant *= 2.f;
}

float CTweakGui::FaceReflectionDistanceDebugValueToActualValue(float v) {
  return 0.2f + 0.015f * v;
}

float CTweakGui::FaceReflectionHeightDebugValueToActualValue(float v) { return 0.005f * v - 0.05f; }

float CTweakGui::FaceReflectionAspectDebugValueToActualValue(float v) { return 1.f + 0.05f * v; }

float CTweakGui::FaceReflectionOrthoWidthDebugValueToActualValue(float v) {
  return 0.02f + 0.007f * v;
}

float CTweakGui::FaceReflectionOrthoHeightDebugValueToActualValue(float v) {
  return 0.02f + 0.007f * v;
}
