object_base: orig/R3IJ01_00
object: files/rs5mp1jpn_p.dol
hash: 976f4532c4850215b766e2f9330b0f711e48d925
symbols: config/R3IJ01_00/symbols.txt
splits: config/R3IJ01_00/splits.txt
mw_comment_version: 8
