#ifndef __PSHAG_CANIMTREEANIMREADERCONTAINER_HPP__
#define __PSHAG_CANIMTREEANIMREADERCONTAINER_HPP__

namespace urde
{

class CAnimTreeAnimReaderContainer
{
};

}

#endif // __PSHAG_CANIMTREEANIMREADERCONTAINER_HPP__
