#ifndef _ACTORCOMMON
#define _ACTORCOMMON

#include "GameVersions.h"

enum EWeaponCollisionResponseTypes {
  kWCR_None,
  kWCR_Default,
  kWCR_Unknown2,
  kWCR_Metal,
  kWCR_Grass,
  kWCR_Ice,
  kWCR_Goo,
  kWCR_Wood,
  kWCR_Water,
  kWCR_Mud,
  kWCR_Lava,
  kWCR_Sand,
  kWCR_Projectile,
  kWCR_OtherProjectile,
  kWCR_Unknown14,
  kWCR_Unknown15,
  kWCR_EnemyNormal,
  kWCR_EnemySpecial,
  kWCR_EnemyShielded,
  // Enemy Normal
  kWCR_Unknown19,
  kWCR_WarWaspNormal,
  kWCR_Unknown21,
  kWCR_Unknown22,
  kWCR_Unknown23,
  kWCR_Unknown24,
  kWCR_Unknown25,
  kWCR_Unknown26,
  kWCR_Unknown27,
  kWCR_Unknown28,
  kWCR_Unknown29,
  kWCR_Unknown30,
  kWCR_Unknown31,
  kWCR_Unknown32,
  kWCR_Unknown33,
  kWCR_Unknown34,
  kWCR_Unknown35,
  kWCR_Unknown36,
  kWCR_Unknown37,
  kWCR_ChozoGhost,
  kWCR_Unknown39,
  kWCR_Unknown40,
  kWCR_Unknown41,
  kWCR_AtomicBeta,
  kWCR_AtomicAlpha,
#if VERSION >= VERSION_GM8P_00
  kWCR_MetroidPrime,
#endif
  // Enemy Special
  kWCR_Unknown44,
  kWCR_Unknown45,
  kWCR_Unknown46,
  kWCR_Unknown47,
  kWCR_Unknown48,
  kWCR_Unknown49,
  kWCR_Unknown50,
  kWCR_Unknown51,
  kWCR_Unknown52,
  kWCR_Unknown53,
  kWCR_Unknown54,
  kWCR_Unknown55,
  kWCR_Unknown56,
  kWCR_Unknown57,
  kWCR_Unknown58,
  kWCR_Unknown59,
  kWCR_Unknown60,
  kWCR_Unknown61,
  kWCR_Unknown62,
  kWCR_Unknown63,
  kWCR_Unknown64,
  kWCR_Unknown65,
  kWCR_Unknown66,
  kWCR_Unknown67,
  kWCR_Unknown68,
#if VERSION >= VERSION_GM8P_00
  kWCR_MetroidPrimeSpecial,
#endif
  // Enemy Shielded
  kWCR_Unknown69,
  kWCR_Unknown70,
  kWCR_Unknown71,
  kWCR_Unknown72,
  kWCR_Unknown73,
  kWCR_Unknown74,
  kWCR_Unknown75,
  kWCR_Unknown76,
  kWCR_Unknown77,
  kWCR_Unknown78,
  kWCR_Unknown79,
  kWCR_Unknown80,
  kWCR_Unknown81,
  kWCR_Unknown82,
  kWCR_Unknown83,
  kWCR_Unknown84,
  kWCR_Unknown85,
  kWCR_Unknown86,
  kWCR_Unknown87,
  kWCR_Unknown88,
  kWCR_Unknown89,
  kWCR_Unknown90,
  kWCR_Unknown91,
  kWCR_AtomicBetaReflect,
  kWCR_AtomicAlphaReflect,
#if VERSION >= VERSION_GM8P_00
  kWCR_MetroidPrimeReflect,
#endif
  kWCR_Count,
};
enum EUserEventType {
  kUE_Projectile = 0,
  kUE_EggLay = 1,
  kUE_LoopedSoundStop = 2,
  kUE_AlignTargetPos = 3,
  kUE_AlignTargetRot = 4,
  kUE_ChangeMaterial = 5,
  kUE_Delete = 6,
  kUE_GenerateEnd = 7,
  kUE_DamageOn = 8,
  kUE_DamageOff = 9,
  kUE_AlignTargetPosStart = 10,
  kUE_DeGenerate = 11,
  kUE_Landing = 12,
  kUE_TakeOff = 13,
  kUE_FadeIn = 14,
  kUE_FadeOut = 15,
  kUE_ScreenShake = 16,
  kUE_BeginAction = 17,
  kUE_EndAction = 18,
  kUE_BecomeRagDoll = 19,
  kUE_IkLock = 20,
  kUE_IkRelease = 21,
  kUE_BreakLockOn = 22,
  kUE_BecomeShootThrough = 23,
  kUE_RemoveCollision = 24,
  kUE_ObjectPickUp = 25,
  kUE_ObjectDrop = 26,
  kUE_EventStart = 27,
  kUE_EventStop = 28,
  kUE_Activate = 29,
  kUE_Deactivate = 30,
  kUE_SoundPlay = 31,
  kUE_SoundStop = 32,
  kUE_EffectOn = 33,
  kUE_EffectOff = 34,
};

#endif // _ACTORCOMMON
